# Generated by Django 3.1.7 on 2021-03-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0004_auto_20210315_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.TextField()),
                ('post_picture', models.ImageField(upload_to='post_images/')),
                ('post_bkash', models.CharField(max_length=50)),
                ('post_accept', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticate.user_info')),
            ],
        ),
    ]
