# Generated by Django 3.1.7 on 2021-03-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0003_auto_20210317_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_post',
            name='user',
        ),
    ]
