# Generated by Django 3.1.7 on 2021-03-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20210315_1322'),
        ('post_details', '0004_remove_pending_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_post',
            name='user',
            field=models.ForeignKey(default=1521216596, on_delete=django.db.models.deletion.CASCADE, to='authenticate.user_info'),
            preserve_default=False,
        ),
    ]
