# Generated by Django 3.1.7 on 2021-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0006_auto_20210317_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_post',
            name='user',
        ),
        migrations.AddField(
            model_name='pending_post',
            name='user_phone_number',
            field=models.IntegerField(default=1521216596),
            preserve_default=False,
        ),
    ]
