# Generated by Django 3.1.7 on 2021-03-18 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0007_auto_20210317_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_post',
            name='post_given_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
