# Generated by Django 3.1.7 on 2021-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0008_pending_post_post_given_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.IntegerField()),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.TextField()),
                ('post_picture', models.ImageField(upload_to='post_images/')),
                ('post_bkash', models.CharField(max_length=50)),
                ('post_accept', models.BooleanField(default=False)),
                ('post_given_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
