# Generated by Django 3.1.7 on 2021-03-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0009_running_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='running_post',
            old_name='post_accept',
            new_name='done_post',
        ),
    ]
