# Generated by Django 3.1.7 on 2021-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0010_auto_20210319_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_post',
            name='post_bkash',
        ),
        migrations.RemoveField(
            model_name='running_post',
            name='post_bkash',
        ),
        migrations.AddField(
            model_name='pending_post',
            name='post_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pending_post',
            name='post_used_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='running_post',
            name='post_money',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='running_post',
            name='post_used_days',
            field=models.IntegerField(default=0),
        ),
    ]
