# Generated by Django 3.1.7 on 2021-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_phone_numebr', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
