# Generated by Django 3.1.7 on 2021-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_mail',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
