# Generated by Django 3.1.7 on 2021-03-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_phone_numebr',
            new_name='user_phone_number',
        ),
    ]
