# Generated by Django 3.1.7 on 2021-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20210313_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
