# Generated by Django 3.1.7 on 2021-03-18 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20210315_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
