# Generated by Django 3.1.7 on 2021-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_user_info_user_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_card_number',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
