# Generated by Django 3.1.7 on 2021-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selling_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_phone_number', models.IntegerField()),
                ('buyer_phone_number', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('profit_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('selling_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
