# Generated by Django 3.1.7 on 2021-04-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_report',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
